version: '3.8'

services:
  memory-store:
    image: julepai/memory-store:${TAG}
    environment:
      COZO_AUTH_TOKEN: ${COZO_AUTH_TOKEN}
      COZO_PORT: 9070
      COZO_MNT_DIR: /data
      COZO_BACKUP_DIR: /backup
    volumes:
      - cozo_data:/data
      - cozo_backup:/backup
    ports:
      - "9070:9070"

  gateway:
    image: julepai/gateway:${TAG}
    environment:
      GATEWAY_PORT: 80
      JWT_SHARED_KEY: ${JWT_SHARED_KEY}
      AGENTS_API_URL: http://agents-api:8080
      AGENTS_API_KEY: ${AGENTS_API_KEY}
      AGENTS_API_KEY_HEADER_NAME: Authorization
      TRAEFIK_LOG_LEVEL: INFO
    ports:
      - "80:80"

  embedding-service:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    environment:
      MODEL_ID: Alibaba-NLP/gte-large-en-v1.5
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      CLOUDFLARE_API_KEY: ${CLOUDFLARE_API_KEY}
      CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID}
      NVIDIA_NIM_API_KEY: ${NVIDIA_NIM_API_KEY}
      GITHUB_API_KEY: ${GITHUB_API_KEY}
      VOYAGE_API_KEY: ${VOYAGE_API_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      TRUNCATE_EMBED_TEXT: True
    volumes:
      - ~/.cache/huggingface/hub:/data

  agents-api:
    image: julepai/agents-api:${TAG}
    environment:
      AGENTS_API_KEY: ${AGENTS_API_KEY}
      AGENTS_API_KEY_HEADER_NAME: Authorization
      AGENTS_API_HOSTNAME: localhost
      AGENTS_API_PUBLIC_PORT: 80
      AGENTS_API_PROTOCOL: http
      COZO_AUTH_TOKEN: ${COZO_AUTH_TOKEN}
      COZO_HOST: http://memory-store:9070
      DEBUG: False
      EMBEDDING_MODEL_ID: Alibaba-NLP/gte-large-en-v1.5
      INTEGRATION_SERVICE_URL: http://integrations:8000
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      LITELLM_URL: http://litellm:4000
      SUMMARIZATION_MODEL_NAME: gpt-4-turbo
      TEMPORAL_ENDPOINT: temporal:7233
      TEMPORAL_NAMESPACE: default
      TEMPORAL_TASK_QUEUE: julep-task-queue
      TEMPORAL_WORKER_URL: temporal:7233
      WORKER_URL: temporal:7233
    ports:
      - "8080:8080"
    depends_on:
      memory-store:
        condition: service_started

volumes:
  cozo_data:
  cozo_backup: